 apriltag:
    ros__parameters:
        family: 36h11           # tag family, one of 16h5, 25h7, 25h9, 36h10, 36h11, 36artoolkit
        size: 0.050             # tag edge size in meter
        max_hamming: 0          # maximum allowed hamming distance (corrected bits)
        z_up: true              # rotate about x-axis to have Z pointing upwards

        # see "apriltag.h" for more documentation on these optional parameters
        decimate: 1.0           # decimate resolution for quad detection
        blur: 0.45              # sigma of Gaussian blur for quad detection
        refine-edges: 1         # snap to strong gradients
        threads: 2              # number of threads
        refine-decode: 1        # increase the number of detected tags
        refine-pose: 1          # increase the accuracy of the extracted pose
        debug: 0                # write additional debugging images to current working directory

        # optional list of tags
#        tag_ids: []            # tag ID
#        tag_frames: []  # optional frame name
#        tag_sizes: []   # optional tag-specific edge size

        # optional list of tags
#            tag_ids: [9, 14]            # tag ID
#            tag_frames: [base, object]  # optional frame name
#            tag_sizes: [0.162, 0.162]   # optional tag-specific edge size
